server:
  port: 8000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: hellowebmvc
          uri: http://localhost:8001
          predicates:
            - Path=/webmvc/**

